name: deploy

on:
  push:
    branches:
      - feature/docker


jobs:
  tests:
    runs-on: self-hosted

    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.3

    services:
      mysql:
        image: mysql:9.0.1
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Run Testsuite
        run: vendor/bin/phpunit tests/

  deploy:
    needs: tests
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy Code to Working Directory
        run: |
          rsync -av ./ ~/www

      - name: Stop and Remove Existing Containers
        run: |
          cd ~/www/docker
          docker compose down


      - name: Start Docker Containers
        run: |
          cd ~/www/docker
          bash run.sh
