name: deploy

on:
  workflow_run:
    workflows: [ "tests" ]
    branches: [ "feature/docker" ]
    types:
      - completed
  push:
    branches:
      - feature/docker


jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy Code to Working Directory
        run: |
          rsync -av ./ ~/www

      - name: Stop and Remove Existing Containers
        run: |
          cd ~/www/docker
          docker compose down


      - name: Start Docker Containers
        run: |
          cd ~/www/docker
          bash run.sh
